# Detecting Spam

In [12]:
import pandas as pd
import numpy as np
import nltk
import string

In [25]:
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [41]:
df = pd.read_csv("spam.csv", encoding="latin-1")
df.head(5)

                                             Message Class
0  Go until jurong point, crazy.. Available only ...   ham
1                      Ok lar... Joking wif u oni...   ham
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam
3  U dun say so early hor... U c already then say...   ham
4  Nah I don't think he goes to usf, he lives aro...   ham

In [ ]:
df["length"] = df["Message"].apply(len)
df.head(5)

                                             Message Class  length
0  Go until jurong point, crazy.. Available only ...   ham     111
1                      Ok lar... Joking wif u oni...   ham      29
2  Free entry in 2 a wkly comp to win FA Cup fina...  spam     155
3  U dun say so early hor... U c already then say...   ham      49
4  Nah I don't think he goes to usf, he lives aro...   ham      61

In [15]:
def preprocess_words(message):
    message = message.translate(str.maketrans('', '', string.punctuation))
    message = [word for word in message.split() if word.lower() not in stopwords.words('english')]
    words = ''
    for i in message:
        stemmer = SnowballStemmer("english")
        words += stemmer.stem(i) + " "
    return words

In [19]:
text_messages = df["Message"].copy()
text_messages = text_messages.apply(preprocess_words)
text_messages.head(4)

0    go jurong point crazi avail bugi n great world...
1                               ok lar joke wif u oni
2    free entri 2 wkli comp win fa cup final tkts 2...
3                 u dun say earli hor u c alreadi say
Name: Message, dtype: str

In [35]:
vectorizer = TfidfVectorizer(stop_words="english")
features = vectorizer.fit_transform(text_messages)

In [39]:
feature_df = pd.DataFrame(features)

In [60]:
features_train, features_test, label_train, label_test = train_test_split(features, df["Class"], test_size=0.3, stratify=df["Class"], random_state=42)

In [61]:
from sklearn.svm import SVC
from sklearn.naive_bayes import BernoulliNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

In [64]:
svc_model = SVC()
svc_model.fit(features_train, label_train)

label_pred = svc_model.predict(features_test)
f1_score(label_test, label_pred, pos_label="spam")

0.8535353535353535